#!/bin/sh

case "$1" in
	list)
		echo '{ "alfred": { "type": 32 } }'
	;;
	call)
		read json
		
		echo '{'
		alfred -r "$(jsonfilter -s "$json" -e '@.type')" | sed -e 's/^{ \(".*"\), \(".*"\) },$/\1: \2,/g; s/\\x/\\u00/g; $s/,$//'
		#cat /root/solardata.json | sed -e 's/^{ \(".*"\), \(".*"\) },$/\1: \2,/g; s/\\x/\\u00/g; $s/,$//'
		echo '}'
	;;
esac
