#!/bin/sh

case "$1" in
	list)
		echo '{ "solardata": { } }'
	;;
	call)
		echo '{'
		alfred -r 160 | sed -e 's/^{ \(".*"\), \(".*"\) },$/\1: \2,/g; s/\\x/\\u00/g; $s/,$//'
		#cat /root/solardata.json | sed -e 's/^{ \(".*"\), \(".*"\) },$/\1: \2,/g; s/\\x/\\u00/g; $s/,$//'
		echo '}'
	;;
esac
